version: '3.8'
services:
  db:
    image: postgres
    container_name: myPostgresDb
    restart: always
    environment:
      - POSTGRES_USER=postgresUser
      - POSTGRES_PASSWORD=postgresPW
      - POSTGRES_DB=postgresDB
    ports:
      - '5455:5432'
    volumes: 
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
    driver: local